version: "3.9"
services:
   app:
      build: .
      ports:
         - 127.0.0.1:8000:8000
         - 10.104.0.2:8070:8070
         #- 127.0.0.1:8070:8070
      environment:
         - SERVICE_HOST=0.0.0.0
         - SERVICE_PORT=8000
         - MEMCACHE_HOST=memcached
         - MEMCACHE_PORT=11211
      depends_on:
         - memcached
      volumes:
         - ./bmilog:/usr/src/app/log
   app_test:
      build: .
      command: bash -c "cd tests && pytest -k basic tests.py --disable-warnings"
      
      #ports:
      #   - 127.0.0.1:8000:8000
      #   - 10.104.0.2:8070:8070
      environment:
         - SERVICE_HOST=0.0.0.0
         - SERVICE_PORT=9099
         - MEMCACHE_HOST=memcached_test
         - MEMCACHE_PORT=11211

      depends_on:
         - memcached_test
   memcached:
      image: memcached

   memcached_test:
      image: memcached
      
      
